version: '3'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .docker.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .docker.env
    depends_on:
      - db

volumes:
  postgres-data:
